CREATE DATABASE auth;

USE auth;



CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
fname VARCHAR(255) NOT NULL,
lname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
rpassword VARCHAR(255) NOT NULL
);